# This is a basic workflow to help you get started with Actions

name: Pull-files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "testing"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull the script from GitHub
        run: curl -fsSL https://raw.githubusercontent.com/adamane/Jamulus-deploy/main/run_jamulus_on_docker.sh > run_jamulus_on_docker.sh
        # start the Script
      - name: modify the script to execute it
        run: chmod +x run_jamulus_on_docker.sh

      - name: install docker and run the container
        run: run_jamulus_on_docker.sh

      - name: wait 10 seconds
        run: sleep 10

      - name: destroy the container
        run: docker kill jamulus

